<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <TieredCompilation>true</TieredCompilation>
    <ApplicationIcon />
    <Authors>Nexport Solutions</Authors>
    <Company>Nexport Solutions</Company>
    <Copyright>Copyright © Nexport Solutions</Copyright>
    <PackageProjectUrl>www.nexportsolutions.com</PackageProjectUrl>
    <RepositoryType>Git</RepositoryType>
    <OutputPath>..\..\Presentation\Nop.Web\Plugins\Misc.Nexport.Archway</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Areas\Admin\Views\Customer\CustomRegistrationFieldDetails.cshtml" />
    <None Remove="Areas\Admin\Views\_ViewImports.cshtml" />
    <None Remove="logo.jpg" />
    <None Remove="plugin.json" />
    <None Remove="Views\RegistrationField\EditCustomerRegistrationFieldAnswers.cshtml" />
    <None Remove="Views\RegistrationField\_CustomerFields.Control.CustomRender.cshtml" />
    <None Remove="Views\_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nop.Plugin.Misc.Nexport\Nop.Plugin.Misc.Nexport.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj" />
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj" />
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Admin\Views\Customer\CustomRegistrationFieldDetails.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Areas\Admin\Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\RegistrationField\EditCustomerRegistrationFieldAnswers.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\RegistrationField\_CustomerFields.Control.CustomRender.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="27.2.1" />
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
  </Target>

  <Target Name="CopyDllFiles" AfterTargets="NopTarget">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\$(OutDir)\refs\Nop.Plugin.Misc.Nexport.dll" DestinationFolder="$(MSBuildProjectDirectory)\$(OutDir)" />
  </Target>

</Project>
